server:
  port: 8083
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
app:
  file:
    storage-dir: "C:/upload"
    download-prefix: "http://localhost:8888/api/v1/file/media/download/"